language: ruby

before_install: mkdir -p output

install:
  - bundle config --local github.https true
  - bundle --path=.bundle/gems --binstubs=.bundle/.bin

script:
  - bundle exec asciidoctor-revealjs -D output/lectures -a customcss=../styles.css -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0 lectures/*.adoc
  - bundle exec asciidoctor -D output README.adoc

after_success:      
  - cd output ; mv README.html ; cp -R ../images . ; cp ../style.css .
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1